---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksdemo
  region: us-east-1
  version: "1.18"

managedNodeGroups:
  - name: workers-1-18
    instanceType: t2.medium
    privateNetworking: true
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 10
    ssh:
      allow: true
      publicKeyName: naresh
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        autoScaler: true
